{
    'name': 'Uellow Fulfillment by Uellow (FBU)',
    'version': '18.0.1.0.0',
    'category': 'Inventory/Inventory',
    'summary': 'Sub-warehouse per vendor, Continue Selling, variant-level stock tracking',
    'author': 'Uellow W.L.L',
    'website': 'https://uellow.com',
    'depends': [
        'stock',
        'purchase',
        'sale',
        'website_sale',
        'product',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/stock_location_data.xml',
        'views/vendor_location_views.xml',
        'views/restock_request_views.xml',
        'views/product_variant_stock_views.xml',
        'views/fbu_dashboard_views.xml',
        'views/menus.xml',
        'wizard/warehouse_receive_wizard_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
