from . import warranty_policy
from . import warranty_card
from . import warranty_claim
from . import product_template
from . import product_product
from . import account_move
from . import sale_order
from . import pos_order
from . import pos_config
from . import res_config_settings
