from odoo import models, fields, api, _
import logging
import json

_logger = logging.getLogger(__name__)


class SEOProduct(models.Model):
    """SEO data per product — generated by AI, editable by admin."""
    _name = 'uellow.seo.product'
    _description = 'Product SEO Data'
    _rec_name = 'product_id'

    product_id = fields.Many2one(
        'product.template', required=True, ondelete='cascade', index=True,
    )
    # Meta title
    meta_title_en = fields.Char('Meta Title (EN)')
    meta_title_ar = fields.Char('Meta Title (AR)')

    # Meta description
    meta_desc_en = fields.Text('Meta Description (EN)')
    meta_desc_ar = fields.Text('Meta Description (AR)')

    # Keywords
    keywords_en = fields.Char('Keywords (EN)')
    keywords_ar = fields.Char('Keywords (AR)')

    # Schema
    schema_json = fields.Text('Schema Markup JSON')

    # Status
    ai_generated = fields.Boolean('AI Generated', default=False)
    last_generated = fields.Datetime('Last Generated')
    needs_update = fields.Boolean('Needs Update', default=True)

    score = fields.Integer('SEO Score (0-100)', default=0, readonly=True)

    @api.model
    def cron_generate_seo(self):
        """Daily: generate SEO for products missing it."""
        config = self.env['uellow.seo.config'].get_config()
        if not config.active:
            return

        domain = [('website_published', '=', True)]
        if not config.overwrite_existing:
            # Only products without SEO records
            existing_ids = self.search([]).mapped('product_id').ids
            domain.append(('id', 'not in', existing_ids))

        products = self.env['product.template'].search(domain, limit=50)
        for product in products:
            self._generate_for_product(product, config)

    def _generate_for_product(self, product, config=False):
        """Generate SEO data for one product using Claude AI or fallback."""
        if not config:
            config = self.env['uellow.seo.config'].get_config()

        # Basic fallback (no AI)
        title_en = f'{product.name} — Buy Online {config.default_suffix_en}'
        title_ar = f'{product.name} — اشتر أونلاين {config.default_suffix_ar}'
        desc_en = (product.description_sale or product.name or '')[:155]
        desc_ar = desc_en

        # Try AI
        if config.anthropic_api_key:
            try:
                import anthropic
                client = anthropic.Anthropic(api_key=config.anthropic_api_key)
                prompt = f"""Generate SEO metadata for this product on Uellow (Kuwait e-commerce).

Product: {product.name}
Category: {product.categ_id.name if product.categ_id else ''}
Price: {product.list_price:.3f} KD
Description: {(product.description_sale or '')[:300]}

Return JSON only (no markdown):
{{
  "meta_title_en": "...",
  "meta_title_ar": "...",
  "meta_desc_en": "...",
  "meta_desc_ar": "...",
  "keywords_en": "...",
  "keywords_ar": "..."
}}"""
                msg = client.messages.create(
                    model='claude-sonnet-4-20250514',
                    max_tokens=400,
                    messages=[{'role': 'user', 'content': prompt}],
                )
                text = msg.content[0].text.strip()
                import re
                text = re.sub(r'^```json?\s*', '', text)
                text = re.sub(r'\s*```$', '', text)
                data = json.loads(text)
                title_en = data.get('meta_title_en', title_en)
                title_ar = data.get('meta_title_ar', title_ar)
                desc_en = data.get('meta_desc_en', desc_en)
                desc_ar = data.get('meta_desc_ar', desc_ar)
            except Exception as e:
                _logger.warning('SEO AI generation failed for %s: %s', product.name, e)

        # Schema markup
        schema = {}
        if config.schema_markup:
            schema = {
                '@context': 'https://schema.org',
                '@type': 'Product',
                'name': product.name,
                'offers': {
                    '@type': 'Offer',
                    'price': str(product.list_price),
                    'priceCurrency': 'KWD',
                    'availability': 'https://schema.org/InStock',
                }
            }

        # Score estimation
        score = 0
        if title_en and len(title_en) >= 30:
            score += 25
        if desc_en and len(desc_en) >= 100:
            score += 25
        if title_ar:
            score += 25
        if schema:
            score += 25

        existing = self.search([('product_id', '=', product.id)], limit=1)
        vals = {
            'product_id': product.id,
            'meta_title_en': title_en[:60],
            'meta_title_ar': title_ar[:60],
            'meta_desc_en': desc_en[:155],
            'meta_desc_ar': desc_ar[:155],
            'schema_json': json.dumps(schema, ensure_ascii=False),
            'ai_generated': bool(config.anthropic_api_key),
            'last_generated': fields.Datetime.now(),
            'needs_update': False,
            'score': score,
        }
        if existing:
            existing.write(vals)
        else:
            self.create(vals)

        # Also update product's website_meta_title/description if fields exist
        try:
            product.website_meta_title = title_en
            product.website_meta_description = desc_en
        except Exception:
            pass
