apiVersion: v1
kind: Secret
metadata:
  name: odoo-secrets
  namespace: odoo
type: Opaque
stringData:
  db-password: odoo
  db-user: odoo
  admin-password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: odoo
type: Opaque
stringData:
  postgres-password: postgres
  postgres-user: postgres
  postgres-db: postgres
