{
    'name': 'Uellow Reviewers',
    'version': '18.0.1.0.0',
    'category': 'Website',
    'summary': 'Human reviewer system with commissions for Uellow',
    'author': 'Uellow',
    'depends': ['website', 'website_sale', 'sale_management', 'uellow_ai_engine', 'uellow_mobile_manager'],
    'data': [
        'security/ir.model.access.csv',
        'data/config_data.xml',
        'data/points_cron.xml',
        'views/reviewer_views.xml',
        'views/reviewer_points_views.xml',
        'views/reviewers_landing_templates.xml',
        'views/reviewer_portal_templates.xml',
        'views/reviewer_product_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'uellow_reviewers/static/src/css/reviewers.css',
            'uellow_reviewers/static/src/js/reviewers.js',
            'uellow_reviewers/static/src/js/reviewers_portal.js',
            'uellow_reviewers/static/src/css/reviewer_product.css',
            'uellow_reviewers/static/src/js/reviewer_product.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
