# -*- coding: utf-8 -*-
{
    'name': 'Odoo UPayments',
    'maintainer': 'UPayments',
    "author": 'UPayments',
    "website": 'https://upayments.com/',
    'company': 'https://upayments.com/',
    'version': '18.0',
    'license': 'OPL-1',
    'category': 'Accounting/Payment Providers',
    'depends': ['base', 'payment', 'website_sale', 'web', 'contacts', 'account_payment'],
    'external_dependencies': {'python': ['bcrypt'], },
    'data': [
        'views/payment_upayments_templates.xml',
        'views/payment_views.xml',
        'views/res_partner.xml',
        'views/payment_token.xml',
        'views/payment_transaction.xml',
        'wizard/payment_refund_wizard.xml',
        'wizard/payment_link_generate_wizard.xml',
        'data/payment_method_data.xml',
        'data/payment_provider_data.xml',
    ],
    'uninstall_hook': 'uninstall_hook',
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': True,
}
