# -*- coding: utf-8 -*-
{
    'name': 'Uellow Mobile App Manager',
    'version': '18.0.2.0.0',
    'category': 'Website/Mobile',
    'summary': 'Full control panel for the Uellow Flutter mobile application',
    'author': 'Uellow',
    'website': 'https://uellow.com',
    'depends': ['base', 'website', 'website_sale', 'sale', 'product', 'web', 'delivery',
                'loyalty', 'stock', 'purchase',
                'dev_facebook_shop_integration', 'delivery_carrier_portal', 'uellow_multivendor',
                'uellow_checkout', 'uellow_bundles'],
    'data': [
        'security/ir.model.access.csv',
        'views/customer_notification_views.xml',
        'views/mobile_dashboard_views.xml',
        'views/mobile_slider_views.xml',
        'views/mobile_category_icon_views.xml',
        'views/mobile_product_slider_views.xml',
        'views/mobile_feature_banner_views.xml',
        'views/mobile_notification_views.xml',
        'views/mobile_app_setting_views.xml',
        'views/mobile_app_ad_views.xml',
        'views/mobile_promotion_views.xml',
        'views/mobile_newcustomer_views.xml',
        'views/vendor_promotions_templates.xml',
        'views/mobile_session_views.xml',
        'views/mobile_popup_views.xml',
        'views/mobile_extras_views.xml',
        'views/sale_order_website_views.xml',
        'views/sale_order_kanban_views.xml',
        'views/menu_views.xml',
        'views/search_log_views.xml',
        'views/uellow_delivery_zone_views.xml',
        'views/sale_order_cancel_views.xml',
        'views/mobile_category_slide_views.xml',
        'views/mobile_announcement_views.xml',
        'views/cart_share_templates.xml',
        'views/website_selective_checkout_templates.xml',
        'views/product_website_extra_views.xml',
        'views/partner_address_views.xml',
        'views/mobile_country_website_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'uellow_mobile_manager/static/src/css/mobile_manager.css',
            'uellow_mobile_manager/static/src/css/sale_kanban.css',
            'uellow_mobile_manager/static/src/js/dashboard_template.xml',
            'uellow_mobile_manager/static/src/js/dashboard.js',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'license': 'LGPL-3',
}
