apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: odoo-staging

bases:
  - ../../

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: odoo-deployment
    count: 1
  - name: postgres-deployment
    count: 1

images:
  - name: ghcr.io/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    newTag: staging
