{
    'name': 'Uellow Multi-Vendor Marketplace',
    'version': '18.0.1.0.0',
    'category': 'eCommerce',
    'summary': 'Multi-vendor marketplace — vendor portal, commissions, store pages, flash sales, multi-currency, multi-country',
    'author': 'Uellow W.L.L',
    'website': 'https://uellow.com',
    'depends': [
        'website_sale',
        'sale_management',
        'account',
        'stock',
        'portal',
        'mail',
        'uellow_fulfillment',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence_data.xml',
        'data/commission_data.xml',
        'views/vendor_views.xml',
        'views/vendor_commission_views.xml',
        'views/vendor_wallet_views.xml',
        'views/vendor_store_views.xml',
        'views/flash_sale_views.xml',
        'views/vendor_settings_views.xml',
        'views/portal_templates.xml',
        'views/menus.xml',
        'wizard/vendor_approve_wizard_views.xml',
        'wizard/payout_wizard_views.xml',
        'wizard/product_reject_wizard_views.xml',
        'views/vendor_product_approval_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'uellow_multivendor/static/src/js/marketplace_dashboard.js',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
