# -*- coding: utf-8 -*-
from . import mobile_slider
from . import mobile_category_icon
from . import mobile_product_slider
from . import mobile_feature_banner
from . import mobile_notification
from . import notification_preference
from . import mobile_app_setting
from . import mobile_session
from . import mobile_otp
from . import mobile_popup
from . import mobile_extras
from . import mobile_dashboard
from . import uc_order
from . import sale_order_mobile
from . import mobile_country_website
from . import mobile_flash_sale
from . import uellow_delivery_zone
from . import product_brand_image
from . import wallet
from . import tracking_extras
from . import cart_share
from . import mobile_app_ad
from . import mobile_promotion
from . import mobile_category_slide
